# Generated by Django 4.1.6 on 2023-03-11 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0006_auto_20191115_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='total_morrisons',
            new_name='total_bigbasket',
        ),
        migrations.RenameField(
            model_name='basket',
            old_name='total_sainsburys',
            new_name='total_dmart',
        ),
        migrations.RenameField(
            model_name='basket',
            old_name='total_tesco',
            new_name='total_jiomart',
        ),
    ]
